package ab.common.lib.register;

import ab.api.AdvancedBotanyAPI;
import ab.api.recipe.RecipeAdvancedPlate;
import ab.api.recipe.RecipeAncientAlphirine;
import ab.api.recipe.lexicon.AdvancedPlateCraftPage;
import ab.api.recipe.lexicon.AlphirineCraftPage;
import ab.common.block.tile.TileLebethronCore;
import ab.common.core.handler.ConfigABHandler;
import ab.common.lib.register.AchievementRegister;
import ab.common.lib.register.BlockListAB;
import ab.common.lib.register.ItemListAB;
import java.util.ArrayList;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.text.TextFormatting;
import vazkii.botania.api.BotaniaAPI;
import vazkii.botania.api.lexicon.KnowledgeType;
import vazkii.botania.api.lexicon.LexiconCategory;
import vazkii.botania.api.lexicon.LexiconEntry;
import vazkii.botania.api.lexicon.LexiconPage;
import vazkii.botania.common.lexicon.BasicLexiconEntry;
import vazkii.botania.api.recipe.RecipePetals;
import vazkii.botania.common.block.ModBlocks;
import vazkii.botania.common.item.ModItems;
import vazkii.botania.common.item.block.ItemBlockSpecialFlower;
import vazkii.botania.common.lexicon.BLexiconCategory;

import vazkii.botania.common.lexicon.page.PageImage;
import vazkii.botania.common.lexicon.page.PageText;

public class RecipeListAB {
    public static LexiconCategory categoryForgotten;
    public static RecipeAncientAlphirine lebethroneRecipe;
    public static RecipeAncientAlphirine forgottenLandRecipe;
    public static RecipeAncientAlphirine advancedSparkRecipe;
    public static RecipeAncientAlphirine manaFlowerRecipe;
    public static RecipeAncientAlphirine hopperRecipe;
    public static RecipeAncientAlphirine fateBoardRecipe;
    public static RecipeAdvancedPlate manaStarRecipe;
    public static RecipeAdvancedPlate terrasteelRecipe;
    public static RecipeAdvancedPlate mithrillRecipe;
    public static RecipeAdvancedPlate nebulaRecipe;
    public static RecipePetals alphirineRecipe;
    public static RecipePetals dictariusRecipe;
    public static RecipePetals azartFlowerRecipe;
    public static LexiconEntry advandedAgglomerationPlate;
    public static LexiconEntry forgottenIntro;
    public static LexiconEntry ancientAlphirine;
    public static LexiconEntry lebethronWood;
    public static LexiconEntry lebethronSpreader;
    public static LexiconEntry mithrill;
    public static LexiconEntry manaContainer;
    public static LexiconEntry manaCrystalCube;
    public static LexiconEntry terraHoe;
    public static LexiconEntry manaRings;
    public static LexiconEntry manaFlower;
    public static LexiconEntry mithrillSword;
    public static LexiconEntry nebula;
    public static LexiconEntry blackHalo;
    public static LexiconEntry antigravityCharm;
    public static LexiconEntry nebulaBlaze;
    public static LexiconEntry dictarius;
    public static LexiconEntry manaCharger;
    public static LexiconEntry nebulaArmor;
    public static LexiconEntry freyrSlingshot;
    public static LexiconEntry engineerHopper;
    public static LexiconEntry nebulaRod;
    public static LexiconEntry gameBoard;
    public static LexiconEntry fateBoard;
    public static LexiconEntry richesKey;
    public static LexiconEntry cubeWardrobe;
    public static LexiconEntry sphereNavigation;
    public static LexiconEntry hornPlenty;
    public static LexiconEntry sprawlRod;
    public static LexiconEntry azartFlower;
    public static LexiconEntry aquaSword;
    public static KnowledgeType forgotten;

    public static void init() {
        RecipeListAB.relicInit();
        categoryForgotten = new BLexiconCategory("forgotten", 5);
        BotaniaAPI.addCategory((LexiconCategory)categoryForgotten);
        forgotten = BotaniaAPI.registerKnowledgeType("ab_forgotten", TextFormatting.BLUE, false);
        lebethroneRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(BlockListAB.blockLebethron), new ItemStack(ModBlocks.dreamwood, 1, 0), 15);
        forgottenLandRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(ItemListAB.itemABResource, 1, 3), new ItemStack(ModItems.manaResource, 1, 15), 75);
        advancedSparkRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(ItemListAB.itemAdvancedSpark), new ItemStack(ModItems.spark), 11);
        manaFlowerRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(ItemListAB.itemABResource, 1, 4), new ItemStack(ModBlocks.flower, 1, Short.MAX_VALUE), 32);
        hopperRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(BlockListAB.blockEngineerHopper), new ItemStack(Blocks.HOPPER), 23);
        fateBoardRecipe = AdvancedBotanyAPI.registerAlphirineRecipe(new ItemStack(BlockListAB.blockBoardFate, 1, 1), new ItemStack(BlockListAB.blockBoardFate), 60);
        mithrillRecipe = AdvancedBotanyAPI.registerAdvancedPlateRecipe(new ItemStack(ItemListAB.itemABResource, 1, 0), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModBlocks.storage, 1, 0), new ItemStack(ModItems.manaResource, 1, 18), 2500000, 2479799);
        terrasteelRecipe = AdvancedBotanyAPI.registerAdvancedPlateRecipe(new ItemStack(ModItems.manaResource, 1, 4), new ItemStack(ModItems.manaResource, 1, 2), new ItemStack(ModItems.manaResource, 1, 0), new ItemStack(ModItems.manaResource, 1, 1), 500000, 2743840);
        manaStarRecipe = AdvancedBotanyAPI.registerAdvancedPlateRecipe(new ItemStack(ItemListAB.itemABResource, 1, 2), new ItemStack(ModItems.manaResource, 1, 23), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(Items.NETHER_STAR), 250000, 7064044);
        nebulaRecipe = AdvancedBotanyAPI.registerAdvancedPlateRecipe(new ItemStack(ItemListAB.itemABResource, 1, 5), new ItemStack(ModItems.manaResource, 1, 8), new ItemStack(ModBlocks.storage, 1, 4), new ItemStack(ItemListAB.itemABResource, 1, 1), 25000000, 9246432);
        forgottenIntro = new BasicLexiconEntry("forgottenIntro", categoryForgotten);
        forgottenIntro.setPriority().setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1"), new PageText("2")}).setIcon(new ItemStack(ItemListAB.itemABResource, 1, 3));
        ancientAlphirine = new BasicLexiconEntry("ancientAlphirine", categoryForgotten);
        alphirineRecipe = BotaniaAPI.registerPetalRecipe(ItemBlockSpecialFlower.ofType("ancientAlphirine"), new Object[]{new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.rune, 1, 8), new ItemStack(ModItems.rune, 1, 4), new ItemStack(ModItems.rune, 1, 5), new ItemStack(ModItems.rune, 1, 6), new ItemStack(ModItems.rune, 1, 7), new ItemStack(ModItems.petal, 1, 1), new ItemStack(ModItems.petal, 1, 4)});
        ancientAlphirine.setPriority().setKnowledgeType(BotaniaAPI.elvenKnowledge).setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1"), new PageImage("2", "ab:textures/misc/ancientAlphirine.png"), BotaniaAPI.internalHandler.petalRecipePage(".petalCraft", alphirineRecipe), new AlphirineCraftPage(ancientAlphirine, forgottenLandRecipe.getOutput(), ".alphirineCraft")}).setIcon(ItemBlockSpecialFlower.ofType("ancientAlphirine"));
        advandedAgglomerationPlate = new BasicLexiconEntry("advancedPlate", categoryForgotten);
        advandedAgglomerationPlate.setPriority().setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "agglomeration_plate")), new AdvancedPlateCraftPage(advandedAgglomerationPlate, terrasteelRecipe.getOutput(), ".abCraft0"), new AdvancedPlateCraftPage(advandedAgglomerationPlate, manaStarRecipe.getOutput(), ".abCraft1")}).setIcon(new ItemStack(BlockListAB.blockABPlate));
        lebethronSpreader = new BasicLexiconEntry("lebethronSpreader", categoryForgotten);
        lebethronSpreader.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "ab_spreader"))}).setIcon(new ItemStack(BlockListAB.blockABSpreader));
        lebethronWood = new BasicLexiconEntry("lebethronWood", categoryForgotten);
        lebethronWood.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new AlphirineCraftPage(lebethronWood, lebethroneRecipe.getOutput(), ".alphirineCraft"), BotaniaAPI.internalHandler.craftingRecipePage(".craft0", new ResourceLocation("advanced_botany", "lebethron_1")), BotaniaAPI.internalHandler.craftingRecipePage(".craft1", new ResourceLocation("advanced_botany", "lebethron_2")), BotaniaAPI.internalHandler.craftingRecipePage(".craft2", new ResourceLocation("advanced_botany", "lebethron_3")), BotaniaAPI.internalHandler.craftingRecipePage(".craft3", new ResourceLocation("advanced_botany", "lebethron_4")), new PageText("1"), BotaniaAPI.internalHandler.multiblockPage(".structure", TileLebethronCore.makeMultiblockSet())}).setIcon(new ItemStack(BlockListAB.blockLebethron));
        mithrill = new BasicLexiconEntry("mithrill", categoryForgotten);
        mithrill.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new AdvancedPlateCraftPage(mithrill, mithrillRecipe.getOutput(), ".abCraft"), new PageText("1"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "mithrill_multi_tool"))}).setIcon(new ItemStack(ItemListAB.itemMihrillMultiTool));
        manaContainer = new BasicLexiconEntry("manaContainer", categoryForgotten);
        manaContainer.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft0", new ResourceLocation("advanced_botany", "mana_container")), BotaniaAPI.internalHandler.craftingRecipePage(".craft1", new ResourceLocation("advanced_botany", "mana_container_1")), BotaniaAPI.internalHandler.craftingRecipePage(".craft2", new ResourceLocation("advanced_botany", "mana_container_2")), new PageText("1"), new AlphirineCraftPage(manaContainer, advancedSparkRecipe.getOutput(), ".alphirineCraft")}).setIcon(new ItemStack(BlockListAB.blockManaContainer));
        manaCrystalCube = new BasicLexiconEntry("manaCrystalCube", BotaniaAPI.categoryMana);
        manaCrystalCube.setKnowledgeType(BotaniaAPI.elvenKnowledge).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "mana_crystal_cube"))}).setIcon(new ItemStack(BlockListAB.blockManaCrystalCube));
        terraHoe = new BasicLexiconEntry("terraHoe", BotaniaAPI.categoryTools);
        terraHoe.setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "terra_hoe"))}).setIcon(new ItemStack(ItemListAB.itemTerraHoe));
        manaRings = new BasicLexiconEntry("manaRings", categoryForgotten);
        manaRings.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft0", new ResourceLocation("advanced_botany", "mithrill_ring")), BotaniaAPI.internalHandler.craftingRecipePage(".craft1", new ResourceLocation("advanced_botany", "nebula_ring"))}).setIcon(new ItemStack(ItemListAB.itemMithrillRing));
        AdvancedBotanyAPI.registerFarmlandSeed(Blocks.CARROTS, 3);
        manaFlower = new BasicLexiconEntry("manaFlower", categoryForgotten);
        manaFlower.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new AlphirineCraftPage(manaFlower, manaFlowerRecipe.getOutput(), ".alphirineCraft"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "mana_flower"))}).setIcon(new ItemStack(ItemListAB.itemManaFlower));
        mithrillSword = new BasicLexiconEntry("mithrillSword", categoryForgotten);
        mithrillSword.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "mithrill_sword"))}).setIcon(new ItemStack(ItemListAB.itemMithrillSword));
        dictariusRecipe = BotaniaAPI.registerPetalRecipe(ItemBlockSpecialFlower.ofType("dictarius"), new Object[]{new ItemStack(ItemListAB.itemABResource, 1, 4), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.manaResource, 1, 5), new ItemStack(ModItems.rune, 1, 15), new ItemStack(ModItems.petal, 1, 4), new ItemStack(ModItems.petal, 1, 4), new ItemStack(ModItems.petal, 1, 1)});
        dictarius = new BasicLexiconEntry("dictarius", BotaniaAPI.categoryGenerationFlowers);
        dictarius.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1"), BotaniaAPI.internalHandler.petalRecipePage(".petalCraft", dictariusRecipe)});
        nebula = new BasicLexiconEntry("nebula", categoryForgotten);
        nebula.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new AdvancedPlateCraftPage(nebula, nebulaRecipe.getOutput(), ".abCraft")});
        blackHalo = new BasicLexiconEntry("blackHalo", BotaniaAPI.categoryTools);
        blackHalo.setKnowledgeType(BotaniaAPI.elvenKnowledge).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "black_halo"))});
        antigravityCharm = new BasicLexiconEntry("antigravityCharm", BotaniaAPI.categoryTools);
        antigravityCharm.setKnowledgeType(BotaniaAPI.elvenKnowledge).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "antigravity_charm"))}).setIcon(new ItemStack(ItemListAB.itemAntigravityCharm));
        nebulaBlaze = new BasicLexiconEntry("nebulaBlaze", categoryForgotten);
        nebulaBlaze.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "nebula_blaze"))});
        if (ConfigABHandler.hasManaCharger) {
            manaCharger = new BasicLexiconEntry("manaCharger", categoryForgotten);
            manaCharger.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "mana_charger"))});
        }
        nebulaArmor = new BasicLexiconEntry("nebulaArmor", categoryForgotten);
        nebulaArmor.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1"), BotaniaAPI.internalHandler.craftingRecipePage(".craft0", new ResourceLocation("advanced_botany", "nebula_helm")), BotaniaAPI.internalHandler.craftingRecipePage(".craft1", new ResourceLocation("advanced_botany", "nebula_chest")), BotaniaAPI.internalHandler.craftingRecipePage(".craft2", new ResourceLocation("advanced_botany", "nebula_legs")), BotaniaAPI.internalHandler.craftingRecipePage(".craft3", new ResourceLocation("advanced_botany", "nebula_boots"))});
        engineerHopper = new BasicLexiconEntry("engineerHopper", categoryForgotten);
        engineerHopper.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new PageImage("1", "ab:textures/misc/engineerHopper.png"), new PageText("2"), new PageText("3"), new PageText("4"), new AlphirineCraftPage(engineerHopper, hopperRecipe.getOutput(), ".alphirineCraft")});
        nebulaRod = new BasicLexiconEntry("nebulaRod", categoryForgotten);
        nebulaRod.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "nebula_rod"))});
        gameBoard = new BasicLexiconEntry("gameBoard", BotaniaAPI.categoryMisc);
        gameBoard.setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "board_fate"))});
        fateBoard = new BasicLexiconEntry("fateBoard", categoryForgotten);
        fateBoard.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), new AlphirineCraftPage(fateBoard, fateBoardRecipe.getOutput(), ".alphirineCraft")});
        freyrSlingshot = new BasicLexiconEntry("freyrSlingshot", BotaniaAPI.categoryAlfhomancy);
        freyrSlingshot.setLexiconPages(new LexiconPage[]{new PageText("0"), new PageText("1")});
        richesKey = new BasicLexiconEntry("richesKey", BotaniaAPI.categoryAlfhomancy);
        richesKey.setLexiconPages(new LexiconPage[]{new PageText("0")});
        cubeWardrobe = new BasicLexiconEntry("cubeWardrobe", BotaniaAPI.categoryAlfhomancy);
        cubeWardrobe.setLexiconPages(new LexiconPage[]{new PageText("0")});
        sphereNavigation = new BasicLexiconEntry("sphereNavigation", BotaniaAPI.categoryAlfhomancy);
        sphereNavigation.setLexiconPages(new LexiconPage[]{new PageText("0")});
        hornPlenty = new BasicLexiconEntry("hornPlenty", BotaniaAPI.categoryAlfhomancy);
        hornPlenty.setLexiconPages(new LexiconPage[]{new PageText("0")});
        sprawlRod = new BasicLexiconEntry("sprawlRod", categoryForgotten);
        sprawlRod.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "sprawl_rod"))});
        azartFlowerRecipe = BotaniaAPI.registerPetalRecipe(ItemBlockSpecialFlower.ofType("ardentAzarcissus"), new Object[]{new ItemStack(ItemListAB.itemABResource, 1, 4), new ItemStack(ModItems.petal, 1, 11), new ItemStack(ModItems.petal, 1, 11), new ItemStack(ModItems.petal, 1, 14), new ItemStack(ModItems.petal, 1, 14), new ItemStack(ModItems.petal, 1, 13), new ItemStack(ModItems.manaResource, 1, 5)});
        azartFlower = new BasicLexiconEntry("azartFlower", BotaniaAPI.categoryGenerationFlowers);
        azartFlower.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.petalRecipePage(".petalCraft", azartFlowerRecipe)});
        aquaSword = new BasicLexiconEntry("aquaSword", categoryForgotten);
        aquaSword.setKnowledgeType(forgotten).setLexiconPages(new LexiconPage[]{new PageText("0"), BotaniaAPI.internalHandler.craftingRecipePage(".craft", new ResourceLocation("advanced_botany", "aqua_sword"))});
    }

    public static void relicInit() {
        AdvancedBotanyAPI.diceList.add(new ItemStack(ModItems.dice));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.infiniteFruit));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.kingKey));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.flugelEye));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.thorRing));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.odinRing));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ModItems.lokiRing));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ItemListAB.itemFreyrSlingshot));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ItemListAB.itemTalismanHiddenRiches));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ItemListAB.itemPocketWardrobe));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ItemListAB.itemSphereNavigation));
        AdvancedBotanyAPI.relicList.add(new ItemStack(ItemListAB.itemHornPlenty));
    }
}
