package ab.client.model.armor;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.monster.EntitySkeleton;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.EnumAction;
import net.minecraft.item.ItemStack;
import net.minecraft.util.math.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelArmorWildHunt extends ModelBiped {
    private final ModelRenderer head;
    private final ModelRenderer cube_r1;
    private final ModelRenderer cube_r2;
    private final ModelRenderer cube_r3;
    private final ModelRenderer cube_r4;
    private final ModelRenderer cube_r5;
    private final ModelRenderer cube_r6;
    private final ModelRenderer cube_r7;
    private final ModelRenderer cube_r8;
    private final ModelRenderer cube_r9;
    private final ModelRenderer cube_r10;
    private final ModelRenderer cube_r11;
    private final ModelRenderer cube_r12;
    private final ModelRenderer cube_r13;
    private final ModelRenderer cube_r14;
    private final ModelRenderer cube_r15;
    private final ModelRenderer cube_r16;
    private final ModelRenderer chest;
    private final ModelRenderer cube_r17;
    private final ModelRenderer cube_r18;
    private final ModelRenderer cube_r19;
    private final ModelRenderer cloak;
    private final ModelRenderer cube_r20;
    private final ModelRenderer lArm;
    private final ModelRenderer cube_r21;
    private final ModelRenderer cube_r22;
    private final ModelRenderer cube_r23;
    private final ModelRenderer cube_r24;
    private final ModelRenderer cube_r25;
    private final ModelRenderer cube_r26;
    private final ModelRenderer rArm;
    private final ModelRenderer cube_r27;
    private final ModelRenderer cube_r28;
    private final ModelRenderer cube_r29;
    private final ModelRenderer cube_r30;
    private final ModelRenderer cube_r31;
    private final ModelRenderer cube_r32;
    private final ModelRenderer lLeg;
    private final ModelRenderer cube_r33;
    private final ModelRenderer rLeg;
    private final ModelRenderer cube_r34;
    private final ModelRenderer rBoot;
    private final ModelRenderer lBoot;
    EntityEquipmentSlot slot;

    public ModelArmorWildHunt(EntityEquipmentSlot slot) {
        this.slot = slot;
        this.textureWidth = 64;
        this.textureHeight = 128;
        this.head = new ModelRenderer(this);
        this.head.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.head.cubeList.add(new ModelBox(this.head, 32, 7, -4.0f, -8.0f, -4.0f, 8, 2, 8, 0.25f));
        this.head.cubeList.add(new ModelBox(this.head, 38, 18, -4.0f, -8.6f, -4.0f, 8, 1, 5, 0.0f));
        this.head.cubeList.add(new ModelBox(this.head, 21, 20, -3.0f, -8.6f, 1.0f, 6, 1, 2, 0.0f));
        this.head.cubeList.add(new ModelBox(this.head, 46, 86, -3.5f, -6.0f, 3.0f, 7, 1, 1, 0.1f));
        this.head.cubeList.add(new ModelBox(this.head, 40, 25, 3.0f, -6.2f, -1.8f, 1, 4, 5, 0.1f));
        this.head.cubeList.add(new ModelBox(this.head, 52, 25, -4.0f, -6.2f, -1.8f, 1, 4, 5, 0.1f));
        this.head.cubeList.add(new ModelBox(this.head, 28, 0, -4.0f, -6.3f, -4.0f, 1, 5, 2, 0.1f));
        this.head.cubeList.add(new ModelBox(this.head, 33, 7, 3.0f, -6.3f, -4.0f, 1, 5, 2, 0.1f));
        this.cube_r1 = new ModelRenderer(this);
        this.cube_r1.setRotationPoint(0.0f, 3.8f, -2.7f);
        this.head.addChild(this.cube_r1);
        this.setRotationAngle(this.cube_r1, -0.1745f, 0.0f, 0.1309f);
        this.cube_r1.cubeList.add(new ModelBox(this.cube_r1, 31, 25, 1.7f, -6.7f, -3.0f, 2, 3, 2, -0.2f));
        this.cube_r2 = new ModelRenderer(this);
        this.cube_r2.setRotationPoint(0.0f, 3.8f, -2.7f);
        this.head.addChild(this.cube_r2);
        this.setRotationAngle(this.cube_r2, -0.1745f, 0.0f, -0.1309f);
        this.cube_r2.cubeList.add(new ModelBox(this.cube_r2, 22, 25, -3.7f, -6.7f, -3.0f, 2, 3, 2, -0.2f));
        this.cube_r3 = new ModelRenderer(this);
        this.cube_r3.setRotationPoint(0.0f, 4.0f, -1.0f);
        this.head.addChild(this.cube_r3);
        this.setRotationAngle(this.cube_r3, -0.1309f, 0.0f, 0.0f);
        this.cube_r3.cubeList.add(new ModelBox(this.cube_r3, 21, 12, -1.0f, -13.1f, -2.8f, 2, 1, 6, 0.0f));
        this.cube_r4 = new ModelRenderer(this);
        this.cube_r4.setRotationPoint(0.3f, 4.0f, -1.2f);
        this.head.addChild(this.cube_r4);
        this.setRotationAngle(this.cube_r4, -0.1309f, 0.0f, 0.0f);
        this.cube_r4.cubeList.add(new ModelBox(this.cube_r4, 47, 61, 1.0f, -15.2f, -3.4f, 2, 3, 2, -0.3f));
        this.cube_r4.cubeList.add(new ModelBox(this.cube_r4, 47, 55, -3.6f, -15.2f, -3.4f, 2, 3, 2, -0.3f));
        this.cube_r5 = new ModelRenderer(this);
        this.cube_r5.setRotationPoint(-0.3f, 4.0f, -1.2f);
        this.head.addChild(this.cube_r5);
        this.setRotationAngle(this.cube_r5, 0.2182f, 0.0f, 0.0f);
        this.cube_r5.cubeList.add(new ModelBox(this.cube_r5, 47, 71, -3.0f, -13.0f, 1.2f, 2, 1, 2, -0.1f));
        this.cube_r5.cubeList.add(new ModelBox(this.cube_r5, 47, 67, 1.6f, -13.0f, 1.2f, 2, 1, 2, -0.1f));
        this.cube_r6 = new ModelRenderer(this);
        this.cube_r6.setRotationPoint(0.0f, 4.0f, -1.0f);
        this.head.addChild(this.cube_r6);
        this.setRotationAngle(this.cube_r6, 0.1309f, 0.0f, 0.0f);
        this.cube_r6.cubeList.add(new ModelBox(this.cube_r6, 24, 8, -1.0f, -11.2f, -2.0f, 2, 2, 1, 0.1f));
        this.cube_r7 = new ModelRenderer(this);
        this.cube_r7.setRotationPoint(-0.8f, 5.5f, -0.1f);
        this.head.addChild(this.cube_r7);
        this.setRotationAngle(this.cube_r7, -0.1309f, 1.5708f, 0.0f);
        this.cube_r7.cubeList.add(new ModelBox(this.cube_r7, 56, 43, -1.0f, -15.7f, -6.4f, 2, 3, 2, -0.35f));
        this.cube_r8 = new ModelRenderer(this);
        this.cube_r8.setRotationPoint(0.8f, 4.5f, -0.1f);
        this.head.addChild(this.cube_r8);
        this.setRotationAngle(this.cube_r8, 0.2182f, -1.5708f, 0.0f);
        this.cube_r8.cubeList.add(new ModelBox(this.cube_r8, 56, 68, -1.0f, -13.7f, -1.7f, 2, 3, 2, -0.2f));
        this.cube_r9 = new ModelRenderer(this);
        this.cube_r9.setRotationPoint(0.8f, 5.5f, -0.1f);
        this.head.addChild(this.cube_r9);
        this.setRotationAngle(this.cube_r9, -0.1309f, -1.5708f, 0.0f);
        this.cube_r9.cubeList.add(new ModelBox(this.cube_r9, 56, 49, -1.0f, -15.7f, -6.4f, 2, 3, 2, -0.35f));
        this.cube_r10 = new ModelRenderer(this);
        this.cube_r10.setRotationPoint(-0.8f, 4.5f, -0.1f);
        this.head.addChild(this.cube_r10);
        this.setRotationAngle(this.cube_r10, 0.2182f, 1.5708f, 0.0f);
        this.cube_r10.cubeList.add(new ModelBox(this.cube_r10, 56, 74, -1.0f, -13.7f, -1.7f, 2, 3, 2, -0.2f));
        this.cube_r11 = new ModelRenderer(this);
        this.cube_r11.setRotationPoint(0.0f, 3.9f, -0.7f);
        this.head.addChild(this.cube_r11);
        this.setRotationAngle(this.cube_r11, -0.1309f, 0.0f, 0.0f);
        this.cube_r11.cubeList.add(new ModelBox(this.cube_r11, 56, 62, -1.0f, -15.7f, -6.6f, 2, 3, 2, -0.35f));
        this.cube_r12 = new ModelRenderer(this);
        this.cube_r12.setRotationPoint(0.0f, 3.9f, -0.7f);
        this.head.addChild(this.cube_r12);
        this.setRotationAngle(this.cube_r12, 0.2182f, 0.0f, 0.0f);
        this.cube_r12.cubeList.add(new ModelBox(this.cube_r12, 56, 55, -1.0f, -14.7f, -1.7f, 2, 4, 2, -0.2f));
        this.cube_r13 = new ModelRenderer(this);
        this.cube_r13.setRotationPoint(-1.6f, 3.8f, -1.6f);
        this.head.addChild(this.cube_r13);
        this.setRotationAngle(this.cube_r13, 0.2182f, 0.7854f, 0.0f);
        this.cube_r13.cubeList.add(new ModelBox(this.cube_r13, 47, 43, -1.0f, -13.7f, -1.7f, 2, 3, 2, -0.2f));
        this.cube_r14 = new ModelRenderer(this);
        this.cube_r14.setRotationPoint(1.6f, 3.8f, -1.6f);
        this.head.addChild(this.cube_r14);
        this.setRotationAngle(this.cube_r14, -0.1309f, -0.7854f, 0.0f);
        this.cube_r14.cubeList.add(new ModelBox(this.cube_r14, 0, 0, -1.0f, -14.7f, -6.3f, 2, 3, 2, -0.35f));
        this.cube_r15 = new ModelRenderer(this);
        this.cube_r15.setRotationPoint(1.6f, 3.8f, -1.6f);
        this.head.addChild(this.cube_r15);
        this.setRotationAngle(this.cube_r15, 0.2182f, -0.7854f, 0.0f);
        this.cube_r15.cubeList.add(new ModelBox(this.cube_r15, 47, 49, -1.0f, -13.7f, -1.7f, 2, 3, 2, -0.2f));
        this.cube_r16 = new ModelRenderer(this);
        this.cube_r16.setRotationPoint(-1.6f, 3.8f, -1.6f);
        this.head.addChild(this.cube_r16);
        this.setRotationAngle(this.cube_r16, -0.1309f, 0.7854f, 0.0f);
        this.cube_r16.cubeList.add(new ModelBox(this.cube_r16, 0, 6, -1.0f, -14.7f, -6.3f, 2, 3, 2, -0.35f));
        this.chest = new ModelRenderer(this);
        this.chest.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.chest.cubeList.add(new ModelBox(this.chest, 49, 25, -1.0f, 7.85f, -2.9f, 2, 2, 1, 0.0f));
        this.chest.cubeList.add(new ModelBox(this.chest, 0, 84, -4.0f, 0.9f, -3.1f, 8, 7, 1, 0.0f));
        this.chest.cubeList.add(new ModelBox(this.chest, 19, 85, -2.5f, 4.7f, 1.9f, 5, 6, 1, 0.0f));
        this.chest.cubeList.add(new ModelBox(this.chest, 44, 89, -3.5f, 0.0f, 1.1f, 7, 7, 2, 0.0f));
        this.chest.cubeList.add(new ModelBox(this.chest, 0, 93, -4.0f, 0.0f, -2.0f, 8, 12, 4, 0.2f));
        this.cube_r17 = new ModelRenderer(this);
        this.cube_r17.setRotationPoint(0.0f, -3.0f, 1.2f);
        this.chest.addChild(this.cube_r17);
        this.setRotationAngle(this.cube_r17, 0.0873f, 0.0f, 0.0f);
        this.cube_r17.cubeList.add(new ModelBox(this.cube_r17, 36, 1, -4.0f, 10.1f, -5.1f, 8, 4, 1, -0.1f));
        this.cube_r18 = new ModelRenderer(this);
        this.cube_r18.setRotationPoint(0.0f, 20.5f, 0.8f);
        this.chest.addChild(this.cube_r18);
        this.setRotationAngle(this.cube_r18, 0.0f, 0.0f, 0.0436f);
        this.cube_r18.cubeList.add(new ModelBox(this.cube_r18, 51, 35, 0.9f, -14.0f, -3.9f, 2, 6, 1, -0.1f));
        this.cube_r19 = new ModelRenderer(this);
        this.cube_r19.setRotationPoint(0.0f, 20.5f, 0.8f);
        this.chest.addChild(this.cube_r19);
        this.setRotationAngle(this.cube_r19, 0.0f, 0.0f, -0.0436f);
        this.cube_r19.cubeList.add(new ModelBox(this.cube_r19, 58, 35, -2.9f, -14.0f, -3.9f, 2, 6, 1, -0.1f));
        this.cloak = new ModelRenderer(this);
        this.cloak.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.cube_r20 = new ModelRenderer(this);
        this.cube_r20.setRotationPoint(0.0f, -6.0f, 1.0f);
        this.cloak.addChild(this.cube_r20);
        this.setRotationAngle(this.cube_r20, 0.2182f, 0.0f, 0.0f);
        this.cube_r20.cubeList.add(new ModelBox(this.cube_r20, 0, 71, -3.0f, 4.6f, 1.4f, 6, 10, 0, 0.0f));
        this.lArm = new ModelRenderer(this);
        this.lArm.setRotationPoint(-5.0f, 2.0f, 0.0f);
        this.lArm.cubeList.add(new ModelBox(this.lArm, 31, 95, -3.0f, -2.0f, -2.0f, 4, 4, 4, 0.3f));
        this.lArm.cubeList.add(new ModelBox(this.lArm, 19, 59, -3.0f, 2.0f, -2.0f, 4, 8, 4, 0.1f));
        this.lArm.cubeList.add(new ModelBox(this.lArm, 19, 51, -3.9f, -2.7f, -2.0f, 4, 3, 4, 0.0f));
        this.cube_r21 = new ModelRenderer(this);
        this.cube_r21.setRotationPoint(-1.1f, 10.3f, 0.5f);
        this.lArm.addChild(this.cube_r21);
        this.setRotationAngle(this.cube_r21, -0.1309f, 0.7854f, 0.0f);
        this.cube_r21.cubeList.add(new ModelBox(this.cube_r21, 0, 29, -1.0f, -13.7f, -6.3f, 2, 2, 2, -0.45f));
        this.cube_r22 = new ModelRenderer(this);
        this.cube_r22.setRotationPoint(0.8f, 9.9f, 1.0f);
        this.lArm.addChild(this.cube_r22);
        this.setRotationAngle(this.cube_r22, -0.1309f, 0.0f, 0.0f);
        this.cube_r22.cubeList.add(new ModelBox(this.cube_r22, 9, 51, -3.0f, -14.7f, -3.4f, 2, 3, 2, -0.35f));
        this.cube_r23 = new ModelRenderer(this);
        this.cube_r23.setRotationPoint(0.8f, 9.9f, 1.0f);
        this.lArm.addChild(this.cube_r23);
        this.setRotationAngle(this.cube_r23, 0.2182f, 0.0f, 0.0f);
        this.cube_r23.cubeList.add(new ModelBox(this.cube_r23, 9, 63, -3.0f, -13.0f, 1.2f, 2, 1, 2, -0.1f));
        this.cube_r24 = new ModelRenderer(this);
        this.cube_r24.setRotationPoint(-1.1f, 9.7f, -0.8f);
        this.lArm.addChild(this.cube_r24);
        this.setRotationAngle(this.cube_r24, 0.2182f, 2.3562f, 0.0f);
        this.cube_r24.cubeList.add(new ModelBox(this.cube_r24, 0, 47, -1.0f, -13.7f, -1.7f, 2, 2, 2, -0.3f));
        this.cube_r25 = new ModelRenderer(this);
        this.cube_r25.setRotationPoint(-1.1f, 9.9f, -0.8f);
        this.lArm.addChild(this.cube_r25);
        this.setRotationAngle(this.cube_r25, -0.1309f, 2.3562f, 0.0f);
        this.cube_r25.cubeList.add(new ModelBox(this.cube_r25, 0, 23, -1.0f, -13.7f, -6.3f, 2, 2, 2, -0.45f));
        this.cube_r26 = new ModelRenderer(this);
        this.cube_r26.setRotationPoint(-1.1f, 10.1f, 0.5f);
        this.lArm.addChild(this.cube_r26);
        this.setRotationAngle(this.cube_r26, 0.2182f, 0.7854f, 0.0f);
        this.cube_r26.cubeList.add(new ModelBox(this.cube_r26, 0, 53, -1.0f, -13.7f, -1.7f, 2, 2, 2, -0.3f));
        this.rArm = new ModelRenderer(this);
        this.rArm.setRotationPoint(5.0f, 2.0f, 0.0f);
        this.rArm.cubeList.add(new ModelBox(this.rArm, 19, 72, -1.0f, 2.0f, -2.0f, 4, 8, 4, 0.1f));
        this.rArm.cubeList.add(new ModelBox(this.rArm, 31, 105, -1.0f, -2.0f, -2.0f, 4, 4, 4, 0.3f));
        this.rArm.cubeList.add(new ModelBox(this.rArm, 19, 43, -0.1f, -2.7f, -2.0f, 4, 3, 4, 0.0f));
        this.cube_r27 = new ModelRenderer(this);
        this.cube_r27.setRotationPoint(1.1f, 10.1f, 0.5f);
        this.rArm.addChild(this.cube_r27);
        this.setRotationAngle(this.cube_r27, 0.2182f, -0.7854f, 0.0f);
        this.cube_r27.cubeList.add(new ModelBox(this.cube_r27, 0, 59, -1.0f, -13.7f, -1.7f, 2, 2, 2, -0.3f));
        this.cube_r28 = new ModelRenderer(this);
        this.cube_r28.setRotationPoint(1.1f, 10.3f, 0.5f);
        this.rArm.addChild(this.cube_r28);
        this.setRotationAngle(this.cube_r28, -0.1309f, -0.7854f, 0.0f);
        this.cube_r28.cubeList.add(new ModelBox(this.cube_r28, 0, 35, -1.0f, -13.7f, -6.3f, 2, 2, 2, -0.45f));
        this.cube_r29 = new ModelRenderer(this);
        this.cube_r29.setRotationPoint(1.2f, 10.0f, -0.8f);
        this.rArm.addChild(this.cube_r29);
        this.setRotationAngle(this.cube_r29, -0.1309f, -2.3562f, 0.0f);
        this.cube_r29.cubeList.add(new ModelBox(this.cube_r29, 0, 41, -1.0f, -13.7f, -6.3f, 2, 2, 2, -0.45f));
        this.cube_r30 = new ModelRenderer(this);
        this.cube_r30.setRotationPoint(1.2f, 9.8f, -0.8f);
        this.rArm.addChild(this.cube_r30);
        this.setRotationAngle(this.cube_r30, 0.2182f, -2.3562f, 0.0f);
        this.cube_r30.cubeList.add(new ModelBox(this.cube_r30, 0, 65, -1.0f, -13.7f, -1.7f, 2, 2, 2, -0.3f));
        this.cube_r31 = new ModelRenderer(this);
        this.cube_r31.setRotationPoint(3.3f, 10.0f, 1.0f);
        this.rArm.addChild(this.cube_r31);
        this.setRotationAngle(this.cube_r31, -0.1309f, 0.0f, 0.0f);
        this.cube_r31.cubeList.add(new ModelBox(this.cube_r31, 9, 57, -3.0f, -14.7f, -3.4f, 2, 3, 2, -0.35f));
        this.cube_r32 = new ModelRenderer(this);
        this.cube_r32.setRotationPoint(3.3f, 10.0f, 1.0f);
        this.rArm.addChild(this.cube_r32);
        this.setRotationAngle(this.cube_r32, 0.2182f, 0.0f, 0.0f);
        this.cube_r32.cubeList.add(new ModelBox(this.cube_r32, 9, 67, -3.0f, -13.0f, 1.2f, 2, 1, 2, -0.1f));
        this.lLeg = new ModelRenderer(this);
        this.lLeg.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.lLeg.cubeList.add(new ModelBox(this.lLeg, 48, 103, -4.0f, 0.4f, -2.0f, 4, 8, 4, 0.15f));
        this.cube_r33 = new ModelRenderer(this);
        this.cube_r33.setRotationPoint(0.0f, 11.9f, 1.0f);
        this.lLeg.addChild(this.cube_r33);
        this.setRotationAngle(this.cube_r33, 0.0873f, 0.0f, 0.0f);
        this.cube_r33.cubeList.add(new ModelBox(this.cube_r33, 37, 122, -3.5f, -10.1f, -3.1f, 3, 4, 2, -0.3f));
        this.rLeg = new ModelRenderer(this);
        this.rLeg.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.rLeg.cubeList.add(new ModelBox(this.rLeg, 48, 116, 0.0f, 0.4f, -2.0f, 4, 8, 4, 0.15f));
        this.cube_r34 = new ModelRenderer(this);
        this.cube_r34.setRotationPoint(0.0f, 11.9f, 1.0f);
        this.rLeg.addChild(this.cube_r34);
        this.setRotationAngle(this.cube_r34, 0.0873f, 0.0f, 0.0f);
        this.cube_r34.cubeList.add(new ModelBox(this.cube_r34, 37, 115, 0.5f, -10.1f, -3.1f, 3, 4, 2, -0.3f));
        this.rBoot = new ModelRenderer(this);
        this.rBoot.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.rBoot.cubeList.add(new ModelBox(this.rBoot, 0, 120, -4.0f, 9.0f, -2.8f, 4, 3, 5, 0.25f));
        this.lBoot = new ModelRenderer(this);
        this.lBoot.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.lBoot.cubeList.add(new ModelBox(this.lBoot, 0, 111, 0.0f, 9.0f, -2.8f, 4, 3, 5, 0.25f));
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (entity instanceof EntitySkeleton || entity instanceof EntityZombie) {
            this.setRotationAnglesMonster(f, f1, f2, f3, f4, f5, entity);
        } else {
            this.prepareForRender(entity);
            this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        }
        this.head.showModel = this.slot == EntityEquipmentSlot.HEAD;
        this.chest.showModel = this.slot == EntityEquipmentSlot.CHEST;
        this.lArm.showModel = this.slot == EntityEquipmentSlot.CHEST;
        this.rArm.showModel = this.slot == EntityEquipmentSlot.CHEST;
        this.rLeg.showModel = this.slot == EntityEquipmentSlot.LEGS;
        this.lLeg.showModel = this.slot == EntityEquipmentSlot.LEGS;
        this.lBoot.showModel = this.slot == EntityEquipmentSlot.FEET;
        this.rBoot.showModel = this.slot == EntityEquipmentSlot.FEET;
        this.bipedBody.showModel = false;
        this.bipedHead = this.head;
        this.bipedBody = this.chest;
        this.bipedLeftArm = this.lArm;
        this.bipedRightArm = this.rArm;
        if (this.slot == EntityEquipmentSlot.LEGS) {
            this.bipedLeftLeg = this.lLeg;
            this.bipedRightLeg = this.rLeg;
        } else {
            this.bipedRightLeg = this.rBoot;
            this.bipedLeftLeg = this.lBoot;
        }
        if (this.isChild) {
            float f6 = 2.0f;
            GL11.glPushMatrix();
            GL11.glScalef(1.5f / f6, 1.5f / f6, 1.5f / f6);
            GL11.glTranslatef(0.0f, 16.0f * f5, 0.0f);
            this.bipedHead.render(f5);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef(1.0f / f6, 1.0f / f6, 1.0f / f6);
            GL11.glTranslatef(0.0f, 24.0f * f5, 0.0f);
            this.bipedBody.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedBody.render(f5);
            GL11.glPopMatrix();
        } else {
            this.bipedHead.render(f5);
            this.bipedBody.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedBody.render(f5);
        }
    }

    public void prepareForRender(Entity entity) {
        EntityLivingBase living = (EntityLivingBase) entity;
        this.isSneak = living != null ? living.isSneaking() : false;
        if (living != null && living instanceof EntityPlayer) {
            EntityPlayer player = (EntityPlayer) living;
            ItemStack itemstack = player.getHeldItemMainhand();
            this.leftArmPose = !itemstack.isEmpty() ? ModelBiped.ArmPose.ITEM : ModelBiped.ArmPose.EMPTY;
            this.rightArmPose = !itemstack.isEmpty() && player.getHeldItemOffhand().isEmpty() ? ModelBiped.ArmPose.ITEM : ModelBiped.ArmPose.EMPTY;
            if (itemstack != null && player.getItemInUseCount() > 0) {
                EnumAction enumaction = itemstack.getItemUseAction();
                if (enumaction == EnumAction.BLOCK) {
                    this.leftArmPose = ModelBiped.ArmPose.BLOCK;
                    this.rightArmPose = ModelBiped.ArmPose.BLOCK;
                } else if (enumaction == EnumAction.BOW) {
                    this.rightArmPose = ModelBiped.ArmPose.ITEM;
                }
            }
        }
    }

    public void setRotationAnglesMonster(float limbSwing, float limbSwingAmount, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity p_78087_7_) {
        this.setRotationAngles(limbSwing, limbSwingAmount, p_78087_3_, p_78087_4_, p_78087_5_, p_78087_6_, p_78087_7_);
        float f6 = MathHelper.sin(limbSwing * (float) Math.PI);
        float f7 = MathHelper.sin((1.0f - (1.0f - limbSwingAmount) * (1.0f - limbSwingAmount)) * (float) Math.PI);
        this.bipedLeftArm.rotateAngleZ = 0.0f;
        this.bipedRightArm.rotateAngleZ = 0.0f;
        this.bipedLeftArm.rotateAngleY = -(0.1f - f6 * 0.6f);
        this.bipedRightArm.rotateAngleY = 0.1f - f6 * 0.6f;
        this.bipedLeftArm.rotateAngleX = -1.5707964f;
        this.bipedRightArm.rotateAngleX = -1.5707964f;
        this.bipedLeftArm.rotateAngleX -= f6 * 1.2f - f7 * 0.4f;
        this.bipedRightArm.rotateAngleX -= f6 * 1.2f - f7 * 0.4f;
        this.bipedLeftArm.rotateAngleZ += MathHelper.cos(p_78087_3_ * 0.09f) * 0.05f + 0.05f;
        this.bipedRightArm.rotateAngleZ -= MathHelper.cos(p_78087_3_ * 0.09f) * 0.05f + 0.05f;
        this.bipedLeftArm.rotateAngleX += MathHelper.sin(p_78087_3_ * 0.067f) * 0.05f;
        this.bipedRightArm.rotateAngleX -= MathHelper.sin(p_78087_3_ * 0.067f) * 0.05f;
    }

    public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
